### Read all films

@baseUrl = http://localhost:3000
GET {{baseUrl}}/films


### Read all films
GET {{baseUrl}}/films

### Read film duration > 120min
GET {{baseUrl}}/films?minimum-duration=120

### login
# @name user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
    "username":"user",
    "password":"user"
}

### Create a film
POST {{baseUrl}}/films
Content-Type: application/json

{
    "title":"Magic Green",
    "duration":77,
    "budget":1564646,
    "link":"oui"
}

### Create a film which lacks a property
POST {{baseUrl}}/films


Content-Type: application/json

{
    "content":"Epinards, Brocolis, Olives vertes, Basilic"
}


### Delete film
 identified by 2
DELETE {{baseUrl}}/films/2

### Update the film
 identified by 6
PATCH {{baseUrl}}/films/6
Content-Type: application/json

{
    "title":"Magic Green 2",
    "duration":144,
    "budget":5446,
    "link":"pqjpiuhfqizq"
}
